export const TEAM_CODES = [
  "BA",
  "BOX",
  "CH",
  "DV",
  "FB",
  "FN",
  "GO",
  "HO",
  "LAX",
  "MBB",
  "MGYM",
  "MSOC",
  "MSW",
  "MTEN",
  "RI",
  "TR",
  "VO",
  "WBB",
  "WGYM",
  "WP",
  "WR",
  "WSOC",
  "WSW",
  "WTEN",
  "XC",
];
export const TEAM_MAPPING = {
  BA: "Baseball",
  BOX: "Boxing",
  CH: "Spirit",
  DV: "Diving",
  FB: "Football",
  FN: "Fencing",
  GO: "Golf",
  HO: "Hockey",
  LAX: "Lacrosse",
  MBB: "Men's Basketball",
  MGYM: "Men's Gymnastics",
  MSOC: "Men's Soccer",
  MSW: "Men's Swimming",
  MTEN: "Men's Tennis",
  RI: "Rifle",
  TR: "Track and Field",
  VO: "Volleyball",
  WBB: "Women's Basketball",
  WGYM: "Women's Gymnastics",
  WP: "Water Polo",
  WR: "Wrestling",
  WSOC: "Women's Soccer",
  WSW: "Women's Swimming",
  WTEN: "Women's Tennis",
  XC: "Cross Country",
};
